# -*- coding: utf-8 -*-
"""assignment8.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OIGRlj5l022PShs5M8eZRS6rA24ndtmW
"""

#1.What is the function that creates Regex objects?
---->
  The re.compile() function returns Regex objects.

#2.Why are raw strings often used when creating Regex objects?
------>

  Raw strings are used so that backslashes do not have to be escaped

#3.What does the search() method return?
------>

  The search() method returns Match objects.

#4.How do you get the actual strings that match the pattern from a Match object?
------>

 The group() method returns strings of the matched text.

#5.In the regex created from r'(\d\d\d)-(\d\d\d-\d\d\d\d)', what does group 0 cover? Group 1? Group 2?
-------->

 Group 0 is the entire match, group 1 covers the first set of parentheses, and 
 group 2 covers the second set of parentheses

#6. Parentheses and periods have specific meanings in regular expression syntax. 
#    How would you specify that you want a regex to match actual parentheses and period characters?
------->

       Periods and parentheses can be escaped with a backslash:
        \., \(, and \).

#7.The findall() method returns a list of strings or a list of tuples of strings. What makes it return one or the other?
----->

    If the regex has no groups, a list of strings is returned. If the regex has groups, a list of tuples of strings is returned.

#8.What does the | character signify in regular expressions?
------>

     The  character signifies matching: "either, or" between two groups.

#9.What two things does the ? character signify in regular expressions?
----->


    The ? character can either mean "match zero or one of the preceding group" or be used to signify nongreedy matching.

#10.What is the difference between the + and * characters in regular expressions?
---->

   The + matches one or more. The * matches zero or more.

#11. What is the difference between {4} and {4,5} in regular expression?
------>

   Ans: {4} means that its preceeding group should repeat 4 times. where as {4,5} means that its preceeding group
    should repeat mininum 4 times and maximum 5 times inclusively

#12. What do you mean by the \d, \w, and \s shorthand character classes signify in regular expressions?
------>

   Ans:
    \d, \w and \s are special sequences in regular expresssions in python:
    \w – Matches a word character equivalent to [a-zA-Z0-9_]
    \d – Matches digit character equivalent to [0-9]
    \s – Matches whitespace character (space, tab, newline, etc.)

#13. What do means by \D, \W, and \S shorthand character classes signify in regular expressions?
-------->

   Ans:

 \D, \W and \S are special sequences in regular expresssions in python:
 \W – Matches any non-alphanumeric character equivalent to [^a-zA-Z0-9_]
 \D – Matches any non-digit character, this is equivalent to the set class [^0-9]
 \S – Matches any non-whitespace character

#14. What is the difference between .*? and .*?
------>

    .* is a Greedy mode, which returns the longest string that meets the condition. Whereas .
    *? is a non greedy mode which returns the shortest string that meets the condition.

#15. What is the syntax for matching both numbers and lowercase letters with a character class?

----->

    Ans: The Synatax is Either [a-z0-9] or [0-9a-z]

#16. What is the procedure for making a normal expression in regax case insensitive?
----->

   Ans: We can pass re.IGNORECASE as a flag to make a noraml expression case insensitive

#17. What does the . character normally match? What does it match if re.DOTALL is passed as 2nd argument in re.compile()?
-------->

   Ans: Dot . character matches everything in input except newline character .. By passing re.DOTALL as a flag to re.compile(),
        you can make the dot character match all characters, including the newline character.

#18. If numReg = re.compile(r'\d+'), what will numRegex.sub('X', '11 drummers, 10 pipers, five rings, 4 hen') return?

------>

Ans: The Ouput will be 'X drummers, X pipers, five rings, X hen'

#19. What does passing re.VERBOSE as the 2nd argument to re.compile() allow to do?
------>

Ans: re.VERBOSE will allow to add whitespace and comments to string passed to re.compile().

#20. How would you write a regex that match a number with comma for every three digits? It must match the given following:
-------->

    '42','1,234', '6,368,745'but not the following: '12,34,567' (which has only two digits between the commas) '1234' (which lacks commas)